# MCP Server configurations
MCP_HOST = "127.0.0.1"
TRANSPORT_TYPE = "http"
MCP_PATH = "/mcp"

# Currency Converter MCP Server configurations
CURRENCY_CONVERTER_PORT = 8010
CURRENCY_CONVERTER_ENDPOINT = f"{TRANSPORT_TYPE}://{MCP_HOST}:{CURRENCY_CONVERTER_PORT}{MCP_PATH}"
CURRENCY_CONVERTER_TOOL_NAME = "convert_currency"
CURRENCY_CONVERTER_TASK_NAME = f"task_{CURRENCY_CONVERTER_TOOL_NAME}"

# Datatime Calculator MCP Server configurations
DATETIME_CALCULATOR_PORT = 8011
DATETIME_CALCULATOR_ENDPOINT = f"{TRANSPORT_TYPE}://{MCP_HOST}:{DATETIME_CALCULATOR_PORT}{MCP_PATH}"
DATETIME_CALCULATOR_TOOL_NAME = "get_current_datetime"
DATETIME_CALCULATOR_TASK_NAME = f"task_{DATETIME_CALCULATOR_TOOL_NAME}"

# Agent B configurations
AGENT_B_PORT = 9010
AGENT_B_HOST = MCP_HOST
AGENT_B_URL = f"{TRANSPORT_TYPE}://{AGENT_B_HOST}:{AGENT_B_PORT}/a2a/message"


# CURRENCY RATES
RATES = {
    "USD": 1.0, 
    "EUR": 0.92, 
    "GBP": 0.80, 
    "JPY": 150.0
}

# Console display configurations
LINE_DIVIDER = "-" * 80
NEW_LINE = "\n"